remote_theme: pages-themes/merlot@v0.2.0
title: null
author: Ian Strawn
description: A website where I post a lot of the statistical/analytical things that I do!
plugins:
  - jekyll-remote-theme

kramdown:
  parse_block_html: true



